#' Generate a map of clusters by door-to-door group
#'
#' Using groups generated by `make_groups` (and manually modified by the user),
#' generate simple walk lists for in-person surveying. Exports a printable
#' PDF.
#'
#' When a cluster's group is specified in the manual column, the manual group
#' assignment is used. When a cluster's group is not specified, the automatic
#' group assignment is used. Clusters can be excluded entirely by entering
#' 0 as the manual group.
#'
#' By default, `make_walkmap` includes all groups. To include only certain
#' groups, specify them in a vector as `groups`.
#'
#' By default, `make_walkmap` only shows the map in the console. Specifying
#' a file path in `save` will save a PNG image of the map to disk.
#'
#' @param save A string; the file path to save the image.
#' @param groups A vector of groups to include.
#' @param title The title of the resulting map, if desired.
#' @param subtitle The subtitle of the resulting map, if desired.
#' @param background The background color for the map. Defaults to white.
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr left_join
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_sf_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_brewer
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_void
#' @importFrom magrittr `%>%`
#' @importFrom Polychrome createPalette
#' @importFrom readr read_csv
#' @importFrom sf read_sf
#' @export

make_walkmap <- function(save = NA,
                         groups = NULL,
                         title = NULL,
                         subtitle = NULL,
                         background = "white"
){
  # Definitions
  `%>%` <- magrittr::`%>%`

  # Load group assignments
  assign <- readr::read_csv(
    "Contacts/Assignments.csv", show_col_types = F
  ) %>%
    dplyr::filter(is.na(manual) | manual != 0)

  # Load shapefiles
  county <- sf::read_sf(.cluster$cfg$shape_county) %>%
    dplyr::filter(GEOID %in% as.character(.cluster$cfg$county))
  blocks <- sf::read_sf(.cluster$cfg$shape_block) %>%
    dplyr::filter(
      STATEFP20 == as.character(.cluster$cfg$state) &
        COUNTYFP20 %in% substr(as.character(.cluster$cfg$county), 3, 5)
    )

  # Merge
  clusters <- assign %>%
    dplyr::mutate(
      geoid = as.character(geoid),
      "Group" = factor(
        x = dplyr::case_when(
          manual == "x" ~ NA,
          is.na(manual) | manual == "" ~ as.character(auto),
          .default = as.character(manual)
        ),
        levels = sort(unique(c(assign$manual, assign$auto)))
      )
    ) %>%
    dplyr::left_join(
      dplyr::select(blocks, geoid = GEOID20, lat = INTPTLAT20, long = INTPTLON20,
                    geometry),
      by = "geoid"
    )

  # Filter for groups to include
  if(!is.null(groups)){
    clusters <- clusters %>%
      dplyr::filter(Group %in% as.character(groups))
  }

  # Map
  plot_map <- ggplot2::ggplot() +
    ggplot2::geom_sf(
      ggplot2::aes(geometry = geometry),
      data = county,
      color = "lightblue4",
      linewidth = 1,
      fill = NA
    ) +
    ggplot2::geom_sf(
      ggplot2::aes(fill = Group, geometry = geometry, color = ur),
      data = clusters,
      linewidth = 1.05,
      inherit.aes = F
    ) +
    ggplot2::geom_sf_text(
      ggplot2::aes(label = cluster, geometry = geometry),
      data = clusters,
      size = 2.5
    ) +
    ggplot2::scale_fill_manual(values = unname(Polychrome::createPalette(
      N = length(unique(clusters$Group)),
      seedcolors = c("#F58638", "#008746", "#0098DA"),
      range = c(50, 90),
      target = "normal",
      M = 1000
    ))) +
    ggplot2::labs(
      title = title,
      subtitle = subtitle,
      fill = "Group (assigned)",
      color = "Rural/Urban"
    ) +
    ggplot2::scale_color_brewer(palette = "Accent") +
    ggplot2::theme_void(paper = background) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 0.5),
      plot.subtitle = ggplot2::element_text(hjust = 0.5)
    )

  # Save
  if(!is.na(save)){
    ggplot2::ggsave(save, plot_map, width = 11, height = 8.5, units = "in")
  }

  # Return
  return(plot_map)
}
