#' Export door-to-door walk lists
#'
#' Using groups generated by `make_groups` (and manually modified by the user),
#' generate simple walk lists for in-person surveying. Exports a printable
#' PDF.
#'
#' When a cluster's group is specified in the manual column, the manual group
#' assignment is used. When a cluster's group is not specified, the automatic
#' group assignment is used. Clusters can be excluded entirely by entering
#' 0 as the manual group.
#'
#' By default, `make_walklist` uses an exceedingly simple template to
#' generate walklists. You can create and specify your own template R markdown
#' file in the arguments to generate a custom report, which can be useful for
#' scripts, reminders, stop times, and other instructional text.
#' `custom_walklist` creates a starter template to customize in your Contacts
#' folder.
#'
#' @param template Template file. Defaults to NA.
#' @param cols A vector of cohort file column names to be included in the output.
#' @param ... Objects passed to the environment where the template is built.
#' @importFrom cli style_bold
#' @importFrom cli style_underline
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom knitr kable
#' @importFrom magrittr `%>%`
#' @importFrom readr read_csv
#' @importFrom rlang `!!!`
#' @importFrom rlang as_name
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang inform
#' @importFrom rlang inject
#' @importFrom rmarkdown render
#' @importFrom rstudioapi viewer
#' @importFrom stringr str_detect
#' @importFrom tidyselect any_of
#' @export

make_walklist <- function(template = NA,
                          cols = c("ID", "Name", "Address", "Consent", "Code", "Notes"),
                          ...
){
  # Definitions
  `%>%` <- magrittr::`%>%`
  `!!!` <- rlang::`!!!`

  # Capture dots
  dots <- rlang::enquos(...)

  # Load cohort and group assignments
  cohort <- readr::read_csv(
    paste0("Cohort/", .cluster$cfg$short_name), show_col_types = F
  )
  assign <- readr::read_csv(
    "Contacts/Assignments.csv", show_col_types = F
  ) %>%
    dplyr::filter(is.na(manual) | manual != 0)

  # Reframe and group data for forms, keep only door-to-door prospects
  walk <- cohort %>%
    dplyr::filter(Status %in% c("Enrolled", "Re-enroll", "Not enrolled")) %>%
    dplyr::left_join(
      assign,
      by = dplyr::join_by("Cluster" == "cluster")
    ) %>%
    dplyr::mutate(
      "Address" = dplyr::case_when(
        stringr::str_detect(toupper(Mailing), "PO BOX") ~ paste(
          Physical, City, paste0(State, " ", substr(ZIP, 1, 5)), sep = ", "
        ),
        .default = paste(
          Mailing, City, paste0(State, " ", substr(ZIP, 1, 5)), sep = ", "
        )
      ),
      "Name" = ifelse(Name == "Current Resident", "", Name),
      "Consent" = dplyr::case_when(
        Consent == "Yes" ~ "Yes",
        .default = ""
      ),
      "Code" = "\\begin{tabular}[t]{@{}c@{}}\\hspace{1in}\\end{tabular}",
      "Notes" = "\\begin{tabular}[t]{@{}c@{}}\\underline{\\hspace{2in}} \\\\ \\underline{\\hspace{2in}}\\end{tabular}",
      "Group" = dplyr::case_when(
        manual == "x" ~ NA,
        is.na(manual) | manual == "" ~ auto,
        .default = manual
      )
    ) %>%
    dplyr::filter(!is.na(Group)) %>%
    dplyr::arrange(Group, Cluster, ID) %>%
    dplyr::select(tidyselect::any_of(c(cols, "Group")))

  # Split group tables
  by_group <- list()
  for(i in 1:length(unique(walk$Group))){
    cat(paste0(
      "\rWorking on group table ",
      i,
      " of ",
      length(unique(walk$Group)),
      "."
    ))
    by_group[[i]] <- walk %>%
      dplyr::filter(Group == sort(unique(walk$Group))[[i]]) %>%
      select(-Group)
  }

  # Knit
  knit_env <- list(
    "cluster_cfg" = .cluster$cfg,
    "by_group" = by_group
  )
  if(length(dots) > 0){
    dots <- lapply(dots, rlang::eval_tidy)
    knit_env <- rlang::inject(c(knit_env, !!!dots))
    names(knit_env) <-  c("cluster_cfg", "by_group", rlang::as_name(names(dots)))
  }
  if(is.na(template)){
    rmarkdown::render(
      input = system.file("auto", "make_walklist.Rmd", package = "clusteR"),
      output_dir = paste0(getwd(), "/Contacts"),
      output_file = "Walk List.pdf",
      envir = knit_env,
      quiet = T
    )
  } else {
    rmarkdown::render(
      input = template,
      output_dir = paste0(getwd(), "/Contacts"),
      output_file = "Walk List.pdf",
      envir = knit_env,
      quiet = T
    )
  }
  if(Sys.getenv("RSTUDIO") == "1"){
    rstudioapi::viewer("Contacts/Walk List.pdf")
  } else {
    rlang::inform(
      message = c(
        cli::style_bold("Walk list generated."),
        "i" = paste0("See ", cli::style_underline("Contacts/Walk List.pdf"), ".")
      )
    )
  }
}
