#' Generate a map of clusters by door-to-door group
#'
#' Using groups generated by `make_groups` (and manually modified by the user),
#' generate simple walk lists for in-person surveying. Exports a printable
#' PNG image.
#'
#' When a cluster's group is specified in the manual column, the manual group
#' assignment is used. When a cluster's group is not specified, the automatic
#' group assignment is used. Clusters can be excluded entirely by entering
#' 0 as the manual group.
#'
#' By default, `make_walkmap` includes all groups. To include only certain
#' groups, specify them in a vector as `groups`.
#'
#' By default, `make_walkmap` only shows the map in the console. Specifying
#' a file path in `save` will save a PNG image of the map to disk.
#'
#' @param save A string; the file path to save the image.
#' @param groups A vector of groups to include.
#' @param layers A named vector of tigris layers and border colors; see [`make_map`].
#' @param title The title of the resulting map, if desired.
#' @param subtitle The subtitle of the resulting map, if desired.
#' @param background The background color for the map. Defaults to white.
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr left_join
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom forcats fct
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_sf_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_brewer
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_void
#' @importFrom magrittr `%>%`
#' @importFrom Polychrome createPalette
#' @importFrom readr read_csv
#' @importFrom stringr str_remove
#' @importFrom tidyselect everything
#' @importFrom tidyselect matches
#' @importFrom tidyselect starts_with
#' @importFrom tigris blocks
#' @importFrom tigris counties
#' @export

make_walkmap <- function(save = NA,
                         groups = NULL,
                         layers = c(),
                         title = NULL,
                         subtitle = NULL,
                         background = "white"
){
  # Definitions
  `%>%` <- magrittr::`%>%`

  # Load group assignments
  assign <- readr::read_csv(
    "Contacts/Assignments.csv", show_col_types = F
  ) %>%
    dplyr::filter(is.na(manual) | manual != 0) %>%
    dplyr::mutate(
      group = ifelse(!is.na(manual), manual, auto),
      geoid = as.numeric(stringr::str_remove(geoid, "'")),
      cluster = as.character(cluster)
    )

  # Filter for groups to include
  if(!is.null(groups)){
    assign <- assign %>%
      dplyr::filter(group %in% as.character(groups))
  }

  # Map
  plot_map <- clusteR::make_map(
    assign,
    layers = layers,
    fill = forcats::fct(
      as.character(group),
      levels = as.character(sort(unique(group)))
    ),
    color = ur,
    title = title,
    subtitle = subtitle,
    background = background,
    ggplot2::scale_fill_manual(values = unname(Polychrome::createPalette(
      N = length(unique(assign$group)),
      seedcolors = c("#F58638", "#008746", "#0098DA"),
      range = c(50, 90),
      target = "normal",
      M = 1000
    ))),
    ggplot2::labs(fill = "Group (assigned)"),
    ggplot2::scale_color_brewer(palette = "Accent")
  )

  # Save
  if(!is.na(save)){
    ggplot2::ggsave(save, plot_map, width = 11, height = 8.5, units = "in")
  }

  # Return
  return(plot_map)
}
